# Generated by Django 6.0.6 on 2026-06-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
